package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnfermedadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermedadAllPropertiesEquals(Enfermedad expected, Enfermedad actual) {
        assertEnfermedadAutoGeneratedPropertiesEquals(expected, actual);
        assertEnfermedadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermedadAllUpdatablePropertiesEquals(Enfermedad expected, Enfermedad actual) {
        assertEnfermedadUpdatableFieldsEquals(expected, actual);
        assertEnfermedadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermedadAutoGeneratedPropertiesEquals(Enfermedad expected, Enfermedad actual) {
        assertThat(actual)
            .as("Verify Enfermedad auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermedadUpdatableFieldsEquals(Enfermedad expected, Enfermedad actual) {
        assertThat(actual)
            .as("Verify Enfermedad relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermedadUpdatableRelationshipsEquals(Enfermedad expected, Enfermedad actual) {
        assertThat(actual)
            .as("Verify Enfermedad relationships")
            .satisfies(a -> assertThat(a.getInformes()).as("check informes").isEqualTo(expected.getInformes()));
    }
}
