package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InformeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformeAllPropertiesEquals(Informe expected, Informe actual) {
        assertInformeAutoGeneratedPropertiesEquals(expected, actual);
        assertInformeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformeAllUpdatablePropertiesEquals(Informe expected, Informe actual) {
        assertInformeUpdatableFieldsEquals(expected, actual);
        assertInformeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformeAutoGeneratedPropertiesEquals(Informe expected, Informe actual) {
        assertThat(actual)
            .as("Verify Informe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformeUpdatableFieldsEquals(Informe expected, Informe actual) {
        assertThat(actual)
            .as("Verify Informe relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getResumen()).as("check resumen").isEqualTo(expected.getResumen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformeUpdatableRelationshipsEquals(Informe expected, Informe actual) {
        assertThat(actual)
            .as("Verify Informe relationships")
            .satisfies(a -> assertThat(a.getReceta()).as("check receta").isEqualTo(expected.getReceta()))
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()))
            .satisfies(a -> assertThat(a.getTrabajador()).as("check trabajador").isEqualTo(expected.getTrabajador()))
            .satisfies(a -> assertThat(a.getEnfermedads()).as("check enfermedads").isEqualTo(expected.getEnfermedads()));
    }
}
