package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentoAllPropertiesEquals(Medicamento expected, Medicamento actual) {
        assertMedicamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentoAllUpdatablePropertiesEquals(Medicamento expected, Medicamento actual) {
        assertMedicamentoUpdatableFieldsEquals(expected, actual);
        assertMedicamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentoAutoGeneratedPropertiesEquals(Medicamento expected, Medicamento actual) {
        assertThat(actual)
            .as("Verify Medicamento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentoUpdatableFieldsEquals(Medicamento expected, Medicamento actual) {
        assertThat(actual)
            .as("Verify Medicamento relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getDosis()).as("check dosis").isEqualTo(expected.getDosis()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentoUpdatableRelationshipsEquals(Medicamento expected, Medicamento actual) {
        assertThat(actual)
            .as("Verify Medicamento relationships")
            .satisfies(a -> assertThat(a.getRecetas()).as("check recetas").isEqualTo(expected.getRecetas()));
    }
}
